### ISSUE TITLE
Exploratory Data Analysis in one line of code

### ISSUE THREAD

**Issue by Emekaborisama** [risenW/datasist#2]
In regard to the vision behind Dataist, I dislike when i always have to perform EDA functions in Pandas one after the other like; df.describe, df.shape, df.dtype and so on. I will like to have it all in one line of code.

**Comment by risenW** [comment]
Hi @Emekaborisama , something similar has been implemented as the **describe** function in the **datasist.structdata** module, you should try extending it then.
