### ISSUE TITLE
Function to train and return popular performance metrics of a regression model.

### ISSUE THREAD

**Issue by risenW** [risenW/datasist#23]
A function like train_classifier in the modeling module that accepts a regression model and displays some of the most popular regression metrics. Helps in model comparison. 
@OlaniyiAjayi

**Comment by risenW** [comment]
Fixed issue

**Comment by jcquarto** [comment]
I've experienced the following error *sometimes* (have not been able to determine what conditions cause it yet):

`
cols = ['age']
df = ds.feature_engineering.log_transform(df_train, columns=cols)
`

leads to: 'module object is not callable'

> TypeError                                 Traceback (most recent call last)
<ipython-input-11-86dd37d7d5a6> in <module>
      4 
      5 cols = ['age']
----> 6 df = ds.feature_engineering.log_transform(train_df, columns=cols)

~/miniconda3/envs/minimal_data_science/lib/python3.7/site-packages/datasist/feature_engineering.py in log_transform(data, columns, plot, figsize)
    532     if plot:
    533         for col in columns:
--> 534             _ = plt.figure(figsize = figsize)
    535             plt.subplot(1, 2, 1)
    536             sns.distplot(data[col], color="m", label="Skewness : %.2f" % (df[col].skew()))

TypeError: 'module' object is not callable
