### ISSUE TITLE
Function that compares multiple algorithms

### ISSUE THREAD

**Issue by risenW** [risenW/datasist#24]
A function that accepts a list of models, and trains and compare them according to a given metrics. Result should be displayed as a plot, for easy reading.

**Comment by KennyRich** [comment]
Won't this be computationally expensive?
Will people still have access to tune the hyperparameters.
Or is it that we run a comparison between models after the models has been trained with various algorithms, and they just pass in the results of the model for easy comparison?

**Comment by risenW** [comment]
> Won't this be computationally expensive?
> Will people still have access to tune the hyperparameters.
> Or is it that we run a comparison between models after the models has been trained with various algorithms, and they just pass in the results of the model for easy comparison?

I think this function should simply be used for a getting a base model. No expensive hyperparameter tuning needed.

**Comment by KennyRich** [comment]
Sounds cool then
