### ISSUE TITLE
Add Tests

### ISSUE THREAD

**Issue by MeNsaaH** [risenW/datasist#25]
Tests should be added for all functionality to prevent breaking in future. An CI to can be used to run PRs against to ensure its not breaking any existing functionality

**Comment by Emekaborisama** [comment]
Awesome

**Comment by risenW** [comment]
This is definitely top priority right now. And I'm working on it.

**Comment by MeNsaaH** [comment]
If there are tests, I can help integrate the CI to run the tests and
automate deployments as well

**Comment by risenW** [comment]
Oh great, will roll them out in the coming days, and notify you. 

Cheers

**Comment by risenW** [comment]
I have added some  test, and will continue working on test for the other modules. Travis CI has also been integrated.
