### ISSUE TITLE
Add a function that splits a data set into test and train subsets

### ISSUE THREAD

**Issue by cemeiq** [risenW/datasist#47]

**Comment by risenW** [comment]
@cemeiq  thanks for raising this issue. 
Could you expand more on it, like I'm aware that scikit-learn has a train-test-split function? Is this the same or different?

**Comment by cemeiq** [comment]
@risenW , its functionality is the same. You can close this issue. I plan to contribute in some other module.

**Comment by risenW** [comment]
Not needed
