### ISSUE TITLE
Unable to extract categorical features from dataframe using datasist

### ISSUE THREAD

**Issue by Adeyinka-hub** [risenW/datasist#50]
i once used datasist to extract both numerical and categorical features successfully. Now, i tried to re run my codes, i only see numerical features being extracted and my categorical features is blank.  Even, it extracted all the  69 features in the dataframe as numerical features while categorical features is blank. Surprisingly, it ran perfectly okay before the rerun showing both numerical and categorical features respectively, and due to this i was able to do feature engineering for my test dataset in the first place. Now that i wanted to conduct the same feature engineering for my train dataset, it only extracted numerical features leaving categorical features blank. Knowingfully well after using "dtype" that there are many object features(i.e categorical features) in both train and test datasets. In fact, there are only 25 numerical features out of 69, others are categorical.
What can be the problem? I tried running my codes both on Kaggle notebook and google colab, the same problem keeps persisting.

**Comment by risenW** [comment]
So sorry for the late reply. Its quite strange, are you certain the data has not been processed and the type changed? 

Also, did you try to update datasist

**Comment by Adeyinka-hub** [comment]
Yes i did my brother. i guessed it's because i updated datasist. Though i later used another set of codes to extract my categorical and numerical features. 
    On Tuesday, 7 July 2020, 22:24:09 GMT+1, Rising Odegua <notifications@github.com> wrote:  
 
 


So sorry for the late reply. Its quite strange, are you certain the data has not been processed and the type changed?

Also, did you try to update datasist
