### ISSUE TITLE
Add function to calculate mean squared distance

### ISSUE THREAD

**Issue by risenW** [risenW/datasist#65]
This function will calculate the mae of a Series and return a single value

An example usage will be
```javascript
def calculate_mae(Series):
    //calculate stuffs here
   return 20

```

**Comment by risenW** [comment]
> This function will calculate the mae of a Series and return a single value
> 
> An example usage will be
> 
> ```js
> def calculate_mae(Series):
>     //calculate stuffs here
>    return 20
> ```

This is good, and we want it in datasist

**Comment by E-STAT** [comment]
Hi, I would like to work on this.
